import { usePage } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
import type { SharedPageProps } from '@/types/auth';

const localTranslations = ref<Record<string, Record<string, string>>>({
    en: {},
    ar: {
        // Navigation & Dashboard
        Dashboard: 'لوحة التحكم',
        'User Management': 'إدارة المستخدمين',
        Users: 'المستخدمين',
        'Roles & Permissions': 'الأدوار والصلاحيات',
        Roles: 'الأدوار',
        Permissions: 'الصلاحيات',
        'Permissions Directory': 'دليل الصلاحيات',
        'Activity Logs': 'سجل النشاطات',
        Notifications: 'الإشعارات',
        'Notifications Center': 'مركز الإشعارات',
        Settings: 'الإعدادات',
        Profile: 'الملف الشخصي',
        'Profile settings': 'إعدادات الملف الشخصي',
        'Update your name and email address': 'تحديث اسمك وعنوان بريدك الإلكتروني',
        'Log out': 'تسجيل الخروج',
        'Log in': 'تسجيل الدخول',
        Register: 'إنشاء حساب',
        'Search...': 'بحث...',
        Export: 'تصدير',
        'Export Excel': 'تصدير إكسيل',
        'Export Report': 'تصدير التقرير',
        'Add User': 'إضافة مستخدم',
        'Add New User': 'إضافة مستخدم جديد',
        'Edit User': 'تعديل مستخدم',
        'Create Role': 'إنشاء دور',
        'Create New Role': 'إنشاء دور جديد',
        'Edit Role': 'تعديل دور',
        'Create Permission': 'إنشاء صلاحية',
        'Generate Module Suite': 'توليد صلاحيات وحدة جديدة',
        'Module Name': 'اسم الوحدة / النموذج',
        'This will auto-generate view, create, edit, delete, and export permissions.': 'سيتم تلقائياً توليد صلاحيات العرض، الإضافة، التعديل، الحذف والتصدير.',
        Generate: 'توليد',
        Status: 'الحالة',
        Active: 'نشط',
        Disabled: 'معطل',
        Inactive: 'غير نشط',
        Save: 'حفظ',
        'Save Role': 'حفظ الدور',
        'Save Permission': 'حفظ الصلاحية',
        'Update Role': 'تحديث الدور',
        'Update User': 'تحديث المستخدم',
        Cancel: 'إلغاء',
        Edit: 'تعديل',
        Delete: 'حذف',
        'View Diff': 'عرض التغييرات',
        Actions: 'الإجراءات',
        'Total Users': 'إجمالي المستخدمين',
        'Active Accounts': 'الحسابات النشطة',
        'Configured Roles': 'الأدوار المتاحة',
        'System Dashboard Overview': 'نظرة عامة على لوحة التحكم',
        "Welcome back! Here is what's happening across your platform today.": 'مرحباً بك مجدداً! إليك أحدث ملخص النشاط عبر منصتك اليوم.',
        'Manage user roles, access levels, and security permission assignments.': 'إدارة أدوار المستخدمين، ومستويات الوصول، وتعيينات الصلاحيات.',
        'Manage system accounts, assign roles, and control account activity.': 'إدارة حسابات النظام، وإسناد الأدوار، والتحكم بنشاط الحسابات.',
        'Review system notifications, automated alerts, and background job status updates.': 'مراجعة إشعارات النظام والتنبيهات التلقائية وتحديثات الوظائف الخلفية.',
        'View system permissions categorized by application module.': 'عرض صلاحيات النظام مقسمة حسب وحدة التطبيق.',
        'Monitor all system operations, data modifications, and user action logs.': 'مراقبة كافة عمليات النظام وتعديلات البيانات وسجلات إجراءات المستخدمين.',
        'User Registration Growth': 'نمو تسجيل المستخدمين',
        'Monthly new user accounts registered over the past 6 months.': 'حسابات المستخدمين الجدد المسجلة شهرياً خلال الـ 6 أشهر الماضية.',
        'Role Distribution': 'توزيع الأدوار',
        'User access level breakdown.': 'تفاصيل مستويات وصول المستخدمين.',
        'Recent Audit Logs': 'أحدث سجلات النشاط',
        'Recently Joined Users': 'المستخدمين المنضمين حديثاً',
        'Mark All as Read': 'تعليم الكل كمقروء',
        'Mark all read': 'تعليم الكل كمقروء',
        'Mark read': 'مقروء',
        unread: 'غير مقروء',
        Notification: 'إشعار',
        'View Details': 'عرض التفاصيل',
        'No notifications': 'لا توجد إشعارات',
        'No unread notifications': 'لا توجد إشعارات غير مقروءة',
        'You have unread notifications': 'لديك إشعارات غير مقروءة',
        'View all notifications →': 'عرض جميع الإشعارات ←',
        "You're all caught up! System alerts will appear here when triggered.": 'أنت متابع لكل جديد! ستظهر تنبيهات النظام هنا فور حدوثها.',
        'View All Permissions': 'عرض كافة الصلاحيات',
        'Back to Roles': 'العودة للأدوار',
        'Back to Users': 'العودة للمستخدمين',
        'Assigned user(s)': 'مستخدم(ين) مسندين',
        'Role Name': 'اسم الدور',
        'Full Name': 'الاسم الكامل',
        'Email Address': 'البريد الإلكتروني',
        'Temporary Password': 'كلمة المرور المؤقتة',
        'New Password (Leave blank to keep unchanged)': 'كلمة المرور الجديدة (اتركها فارغة لإبقائها دون تغيير)',
        'Profile Avatar': 'الصورة الشخصية',
        'Assign Roles': 'إسناد الأدوار',
        'Account Status': 'حالة الحساب',
        'Active users can log into the system.': 'المستخدمون النشطون يمكنهم تسجيل الدخول للنظام.',
        'Select All': 'تحديد الكل',
        'Deselect All': 'إلغاء تحديد الكل',
        'Permissions Matrix': 'مصفوفة الصلاحيات',
        'Assign Permissions': 'إسناد الصلاحيات',
        'Select the permissions to assign to this role.': 'اختر الصلاحيات المراد إسنادها لهذا الدور.',
        'Toggle permissions assigned to this role.': 'تعديل الصلاحيات المسندة لهذا الدور.',
        Module: 'وحدة',
        Registered: 'تاريخ التسجيل',
        ratio: 'نسبة',
        'Manage →': 'إدارة ←',
        'View Logs →': 'عرض السجلات ←',
        'View All Logs →': 'عرض كافة السجلات ←',
        'Manage Users →': 'إدارة المستخدمين ←',
        By: 'بواسطة',
        more: 'إضافي',
        'No permissions assigned': 'لا توجد صلاحيات مسندة',
        Showing: 'عرض',
        to: 'إلى',
        of: 'من أصل',
        results: 'نتيجة',
        Page: 'صفحة',
        'All Statuses': 'جميع الحالات',
        'Active Only': 'نشط فقط',
        'Inactive Only': 'غير نشط فقط',
        'All Roles': 'جميع الأدوار',
        User: 'المستخدم',
        'Role(s)': 'الأدوار',
        'No records found': 'لم يتم العثور على نتائج',
        'Try adjusting your filters or search terms.': 'جرب تعديل خيارات البحث أو التصفية.',

        // Auth & Accounts
        'Log in to your account': 'تسجيل الدخول إلى حسابك',
        'Enter your email and password below to log in': 'أدخل بريدك الإلكتروني وكلمة المرور أدناه لتسجيل الدخول',
        'Forgot your password?': 'نسيت كلمة المرور؟',
        'Remember me': 'تذكرني',
        "Don't have an account?": 'ليس لديك حساب؟',
        'Sign up': 'إنشاء حساب جديد',
        'Create an account': 'إنشاء حساب جديد',
        'Enter your details below to create your account': 'أدخل بياناتك أدناه لإنشاء حسابك الجديد',
        'Create account': 'إنشاء الحساب',
        'Already have an account?': 'لديك حساب بالفعل؟',
        'Forgot password': 'نسيت كلمة المرور',
        'Enter your email to receive a password reset link': 'أدخل بريدك الإلكتروني لاستلام رابط إعادة ضبط كلمة المرور',
        'Email password reset link': 'إرسال رابط إعادة ضبط كلمة المرور',
        'Or, return to': 'أو، العودة إلى',
        Name: 'الاسم',
        'Email address': 'البريد الإلكتروني',
        Password: 'كلمة المرور',
        'Confirm password': 'تأكيد كلمة المرور',
        'Reset password': 'إعادة تعيين كلمة المرور',
        'Reset Password': 'إعادة تعيين كلمة المرور',
        'Send password reset link': 'إرسال رابط إعادة ضبط كلمة المرور',
        'Confirm your password': 'تأكيد كلمة المرور',
        'This is a secure area of the application. Please confirm your password before continuing.': 'هذه منطقة آمنة من التطبيق. يرجى تأكيد كلمة المرور قبل المتابعة.',
        Confirm: 'تأكيد',
        'Verify email': 'تأكيد البريد الإلكتروني',
        'Two-factor authentication': 'المصادقة الثنائية',
        'Recovery code': 'رمز الاسترداد',
        'Authentication code': 'رمز المصادقة',
        'Use a recovery code': 'استخدام رمز استرداد',
        'Use an authentication code': 'استخدام رمز المصادقة',
        'Please confirm access to your account by entering the authentication code provided by your authenticator application.': 'يرجى تأكيد الوصول إلى حسابك بإدخال رمز المصادقة المقدم من تطبيق المصادقة الخاص بك.',
        'Please confirm access to your account by entering one of your emergency recovery codes.': 'يرجى تأكيد الوصول إلى حسابك بإدخال أحد رموز الاسترداد الاحتياطية.',
        Code: 'الرمز',
        'or you can': 'أو يمكنك',
        'Enter recovery code': 'أدخل رمز الاسترداد',
        'Confirm with passkey': 'التأكيد بمفتاح المرور',
        'Confirming...': 'جاري التأكيد...',
        'Or confirm with password': 'أو التأكيد بكلمة المرور',
        'Email verification': 'تأكيد البريد الإلكتروني',
        'Please verify your email address by clicking on the link we just emailed to you.': 'يرجى تأكيد بريدك الإلكتروني بالنقر على الرابط المرسل إليك.',
        'A new verification link has been sent to the email address you provided during registration.': 'تم إرسال رابط تأكيد جديد إلى عنوان البريد الإلكتروني الذي قدمته أثناء التسجيل.',
        'Resend verification email': 'إعادة إرسال رسالة التأكيد',
        'Please enter your new password below': 'يرجى إدخال كلمة المرور الجديدة أدناه',
        Continue: 'متابعة',

        // Theme & Appearance
        System: 'النظام',
        Dark: 'داكن',
        Light: 'فاتح',
        system: 'النظام',
        dark: 'داكن',
        light: 'فاتح',
        'Theme Mode': 'نمط المظهر',
        'Switch between light, dark, or system preference theme.': 'التبديل بين النمط الفاتح، الداكن، أو تفضيلات النظام.',
        'Accent Palette': 'لوحة الألوان الأساسية',
        'Select your preferred primary color theme accent.': 'اختر لون التمييز الأساسي المفضل لديك للنظام.',
        Slate: 'رمادي',
        Indigo: 'نيلي',
        Emerald: 'زمرد',
        Violet: 'بنفسجي',
        Rose: 'وردي',
        Amber: 'كهرماني',

        // Settings Pages
        Security: 'الأمان',
        'Security settings': 'إعدادات الأمان',
        Appearance: 'المظهر',
        'Appearance settings': 'إعدادات المظهر',
        'System Settings': 'إعدادات النظام',
        'API Tokens': 'رموز الوصول API',
        'Manage your profile, security, appearance, and system settings': 'إدارة ملفك الشخصي والأمان والمظهر وإعدادات النظام',
        'Update password': 'تحديث كلمة المرور',
        'Ensure your account is using a long, random password to stay secure': 'تأكد من أن حسابك يستخدم كلمة مرور طويلة وعشوائية للبقاء آمناً',
        'Current password': 'كلمة المرور الحالية',
        'New password': 'كلمة المرور الجديدة',
        'Configure general system parameters, default language, and operational status.': 'ضبط معلمات النظام العامة واللغة الافتراضية والحالة التشغيلية.',
        'Application Name': 'اسم التطبيق',
        'Support Contact Email': 'البريد الإلكتروني للدعم',
        'Default Language': 'اللغة الافتراضية',
        'Maintenance Mode': 'وضع الصيانة',
        'When enabled, non-admin users will be prevented from making system updates.': 'عند التفعيل، سيتم منع المستخدمين غير المسؤولين من إجراء تحديثات النظام.',
        'Save Settings': 'حفظ الإعدادات',

        // Maintenance & Errors
        'Under Maintenance': 'تحت الصيانة',
        'System is currently under maintenance. Please try again later.': 'النظام حالياً تحت الصيانة. يرجى المحاولة مرة أخرى لاحقاً.',
        'System is currently under maintenance. Only authorized administrators can log in.': 'النظام حالياً تحت الصيانة. يمكن للمسؤولين المصرّح لهم فقط تسجيل الدخول.',
        'Admin Login': 'تسجيل دخول المسؤول',
        'Log in as Administrator': 'تسجيل الدخول كمسؤول',
        'Page Not Found': 'الصفحة غير موجودة',
        'The page you are looking for does not exist or has been moved.': 'الصفحة التي تبحث عنها غير موجودة أو تم نقلها.',
        'Access Denied': 'تم رفض الوصول',
        'You do not have permission to access this page.': 'ليس لديك إذن للوصول إلى هذه الصفحة.',
        'Server Error': 'خطأ في الخادم',
        'Something went wrong on our end. Please try again later.': 'حدث خطأ ما من جانبنا. يرجى المحاولة مرة أخرى لاحقاً.',
        'Go to Homepage': 'الذهاب إلى الصفحة الرئيسية',
        'Refresh Page': 'تحديث الصفحة',

        // Landing & Welcome
        'Creative Starter Dashboard Kit - Laravel 13 & Vue 3 Foundation': 'حزمة لوحة التحكم الإبداعية - الأساس البرمجي لـ لارافيل 13 و فيو 3',
        'Go to Dashboard': 'الانتقال إلى لوحة التحكم',
        'Open Dashboard': 'فتح لوحة التحكم',
        'Explore Demo Account': 'استكشاف حساب العرض',
        'Build Enterprise SaaS Apps': 'بناء تطبيقات المؤسسات و SaaS',
        '10x Faster & Scalable': 'أسرع بـ 10 أضعاف وقابل للتوسع',
        'An opinionated, production-ready dashboard kit equipped with Spatie Roles & Permissions, User Impersonation, Bulk Table Operations, API Access Tokens, System Settings, Activity Audit Trail, and Full RTL Multi-Language Infrastructure.': 'حزمة لوحة تحكم جاهزة للإنتاج مزودة بنظام الأدوار والصلاحيات من Spatie، وانتحال صفة المستخدمين، والعمليات الجماعية للجدول، ورموز وصول API، وإعدادات النظام، وسجل تدقيق النشاط، وبنية تحتية كاملة لدعم متعدد اللغات و RTL.',
        'Automated Pest Tests': 'اختبارات Pest المؤتمنة',
        'RTL & i18n Ready': 'جاهز بالكامل للغة العربية و RTL',
        'Interactive Analytics': 'تحليلات تفاعلية',
        'Built for Enterprise Developers': 'صُمم للمطورين المحترفين والمؤسسات',
        'Everything Included Out-of-the-Box': 'كل ما تحتاجه مدمج وجاهز في الحزمة',
        'User Impersonation': 'انتحال صفة المستخدم',
        'Super Admins can log in as any user with 1 click to debug issues. Features a persistent top banner to exit impersonation anytime.': 'يمكن للمدراء الفائقين تسجيل الدخول كأي مستخدم بضغطة زر لمراجعة المشكلات. تتضمن شريط تنبيه علوي ثابت للخروج من الانتحال في أي وقت.',
        'Permission Matrix & Generators': 'مصفوفة الصلاحيات ومولدات الكود',
        'Spatie Authorization with visual permission assignment grid, plus CLI generator commands (permissions:generate, permissions:sync) and Web UI generator.': 'نظام صلاحيات Spatie مع مصفوفة بصرية لتعيين الصلاحيات، بالإضافة لأوامر توليد الصلاحيات عبر CLI وواجهة المستخدم.',
        'Bulk Data Operations': 'العمليات الجماعية على البيانات',
        'Multi-select checkboxes built directly into DataTable.vue. Perform bulk deletes, activate/disable actions, and custom batch operations.': 'مربعات اختيار متعددة مدمجة في جدول البيانات. تنفيذ الحذف الجماعي والتفعيل والتعطيل والعمليات المجمعة.',
        'Sanctum API Tokens': 'رموز الوصول API عبر Sanctum',
        'Personal access token manager allowing users to issue third-party API keys with custom permissions and token revocation controls.': 'مدير رموز الوصول الشخصية يتيح إصدار مفاتيح API للخدمات الخارجية مع التحكم الكامل في الصلاحيات والإلغاء.',
        'Activity Logs & 1-Click Undo': 'سجلات النشاط والتراجع بضغطة واحدة',
        'Full Spatie Activitylog history with event filtering, side-by-side JSON diff inspector, and 1-click action reversal capabilities.': 'سجل نشاط كامل من Spatie مع تصفية الأحداث وفحص التغييرات والتراجع عن الإجراءات بضغطة زر واحدة.',
        'i18n & Full RTL Support': 'دعم شامل للغات والاتجاه العربي RTL',
        'Complete English (en) & Arabic (ar) translations with automatic text direction switching (dir="rtl" / dir="ltr").': 'ترجمة كاملة باللغتين الإنجليزية والعربية مع تبديل تلقائي لاتجاه النص.',
        'All rights reserved.': 'جميع الحقوق محفوظة.',
        'Created by Eng. Hasan Mohammad Hasan': 'تم التطوير بواسطة م. حسن محمد حسن',
        'Creative Starter Dashboard Kit': 'حزمة لوحة التحكم الإبداعية',

        // Toast Messages
        Success: 'تم بنجاح',
        Error: 'خطأ',
        Warning: 'تنبيه',
        Information: 'معلومات',
    },
});

export function useTrans() {
    const page = usePage<SharedPageProps>();

    const locale = computed(() => page.props.locale || 'en');
    const dir = computed(() => page.props.dir || (locale.value === 'ar' ? 'rtl' : 'ltr'));
    const isRtl = computed(() => dir.value === 'rtl');

    function t(key: string, fallback?: string): string {
        const currentLang = locale.value;

        // 1. Check server-provided translations
        const serverTrans = page.props.translations;
        if (serverTrans && serverTrans[key]) {
            return serverTrans[key];
        }

        // 2. Check local fallback dictionary
        if (localTranslations.value[currentLang] && localTranslations.value[currentLang][key]) {
            return localTranslations.value[currentLang][key];
        }

        return fallback || key;
    }

    return {
        locale,
        dir,
        isRtl,
        t,
    };
}
